### ISSUE TITLE
add iconv

### ISSUE THREAD

**Issue by yuanpeirong** [StephanTLavavej/mingw-distro#104]
if I Use `g++ hello.cpp -o hello.exe -finput-charset=UTF-8 -fexec-charset=gbk` 
will get error：
`cc1plus.exe: error: no iconv implementation, cannot convert from UTF-8 to gbk`

**Comment by StephanTLavavej** [comment]
Sorry, I have no interest in catering to non-Unicode, non-ASCII scenarios. It's 2024 and the world is Unicode now.
