### ISSUE TITLE
"Basic" MinGW distro?

### ISSUE THREAD

**Issue by 636C6F776E** [StephanTLavavej/mingw-distro#105]
Hello! I am looking for a high quality alternative to (abandoned?) TDM-GCC. Your MinGW distro is great however I have a disagreement: in my personal opinion a distro should only contain the following items:

* compiler
* debugger
* binutils
* make

IMPO everything extra is basically a pollutant or at the very least bloat. Extra tools and libraries can (and should?) be managed independently of the above.

I would like to know your reasoning for including things such as Boost, SDL2, LAME etc. I have noticed the same trend in the WinLibs distro and I don't understand it.

Additionally I'd like to know if you'd ever consider releasing a stripped-down alternative version (e.g. *mingw-basic-19.0.exe*).

**Comment by 636C6F776E** [comment]
> a stripped-down alternative version

My mistake! I didn't notice *components.7z* -- thank you for the distro!

**Comment by StephanTLavavej** [comment]
> I would like to know your reasoning for including things such as Boost, SDL2, LAME etc. I have noticed the same trend in the WinLibs distro and I don't understand it.

It's stuff that I use personally - or did, when I had time to program C++ as a hobby.

Yep, I provide components.7z precisely to allow people to create subsets easily.
