### ISSUE TITLE
tar wget confusion.

### ISSUE THREAD

**Issue by nacnud-sco** [StephanTLavavej/mingw-distro#107]
Likely it is that I don't understand the "build scripts", but why do they have a hard coded "version" tar file in them?

If the version is well known, why does the script not just try to `wget`? They URLS are well known. 

If the version is "just the latest", then the scripts should just go to the same URl and get the latest versions from there. 

What did I miss, about the point of these things? 

Sorry, and thanks. :)

**Comment by StephanTLavavej** [comment]
> If the version is well known, why does the script not just try to wget? They URLS are well known.

The sources are currently 2.4 GB, so I keep local copies, and download new ones only when updating those components.

> If the version is "just the latest", then the scripts should just go to the same URl and get the latest versions from there.

It's critical to pin a script to a specific version, because new versions often need new incantations (even if the directory names etc. were generalized).
