### ISSUE TITLE
mingw-w64's source tar shouldn't emit pax_global_header

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#13]
Extracting mingw-w64's source tar with 7-Zip emits a `pax_global_header` file, which I have to delete.

**Comment by ismail** [comment]
Just to tell why this happens. New versions of tar defaults to POSIX format which neither 7-zip nor WinRAR can handle correctly. Either you use a new gnu tar to extract or mingw-w64 just start compressing their tarballs with tar --format=gnu ...

**Comment by ismail** [comment]
Since this is not just an aesthetic issue (the tarball might be extracted incorrectly), I reported this to upstream: http://article.gmane.org/gmane.comp.gnu.mingw.w64.general/12015

**Comment by StephanTLavavej** [comment]
Thanks @ismail ! The next time I update mingw-w64, I'll use the zip, modify my script accordingly, and close this issue.

**Comment by ismail** [comment]
With 4.0.5 release we have zip files: 

https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v4.0.5.zip
https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v4.0.5.zip.asc
https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v4.0.5.zip.sig

We can close this bug now :-)

**Comment by StephanTLavavej** [comment]
Thanks for letting me know. I'll close this when I build a new distro and update my scripts.
