### ISSUE TITLE
MSYS2's installation annoyingly requires pacman.exe termination

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#20]
MSYS2's installation process, as described by [my README.md](https://github.com/StephanTLavavej/mingw-distro/blob/master/README.md), has become very annoying. One part will disappear (the `update-core` step) when the base archive is updated, but that won't fix the major new annoyance.

Specifically, when MSYS2 must be recycled, sometimes `pacman.exe` needs to be terminated manually.

It would be great if MSYS2 could be fixed somehow to not require manual termination of processes. Having to red-X the window repeatedly is tolerable, but no more.

**Comment by mmicko** [comment]
pacman -Sy
pacman -S bash pacman msys2-runtime --noconfirm --needed
pacman -Su --noconfirm

We use these steps when doing upgrades. In cas something is installed in 2nd step, you need to restart msys2 shell

**Comment by StephanTLavavej** [comment]
Yeah, but when you restart the shell, is pacman.exe still running? This is new behavior (it didn't previously happen).

**Comment by StephanTLavavej** [comment]
I just checked, and `--noconfirm` causes the initial yes/no prompt to be skipped (which is nice) but it also causes the final

```
warning: terminate MSYS2 without returning to shell and check for updates again
warning: for example close your terminal window instead of calling exit
```

to not wait for input. Instead, it returns to the shell, which seems unwise. pacman.exe terminates and nothing appears to go wrong after red-Xing the window, but I don't think I want to directly disobey MSYS2's warning, and their wiki doesn't suggest `--noconfirm`.

**Comment by StephanTLavavej** [comment]
I haven't seen this happen with the 20161025 build, but maybe that's because pacman hasn't been updated since then.

**Comment by StephanTLavavej** [comment]
Right now, it appears that a gibberish-named process needs to be terminated, which is actually worse than needing to terminate pacman.exe.

**Comment by StephanTLavavej** [comment]
Right now, I'm not observing either pacman.exe or the gibberish-named process lingering. However, the "Terminal" hangs after the first invocation of `pacman -Syuu`. After everything is updated, Task Manager shows "MSYS2 terminal" running, which leads me to suspect that the terminal is being patched and that's why it's hanging.

**Comment by StephanTLavavej** [comment]
With the 20170918 build, the lingering pacman.exe and hanging Terminal are gone, but the gibberish-named process is back.

**Comment by SHA121** [comment]
I install MSYS2 and generates keys, but now I need encryption and decryption?

**Comment by StephanTLavavej** [comment]
The 2021-07-25 build appears to behave properly.
