### ISSUE TITLE
Please ship gmp/mpfr/mpc in this distro

### ISSUE THREAD

**Issue by lichray** [StephanTLavavej/mingw-distro#22]
They are needed when building this distro anyway.  And now I need them as 3rd party libraries.

**Comment by StephanTLavavej** [comment]
This isn't the first request I've gotten, so I'll consider it.

**Comment by StephanTLavavej** [comment]
Hmm, I've decided against this. My free time is too limited to answer support requests for yet more libraries I don't use. And if I go back to in-tree builds, I'd need a separate step to build these anyways.
