### ISSUE TITLE
libstdc++fs.a is not included

### ISSUE THREAD

**Issue by tcbrindle** [StephanTLavavej/mingw-distro#23]
GCC 6 includes an implementation of the Filesystem TS, but the symbols are in a separate static library, `libstdc++fs.a` (see "Experimental Library Extensions" section in [this link](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dynamic_or_shared.html), or Jonathan Wakely's answer on [this SO question](https://stackoverflow.com/questions/33149878/experimentalfilesystem-linker-error)). This separate library is not present in the MinGW distro.

The documentation mentions that Windows support is "rudimentary", but it would be nice to be able to try it and see how rudimentary it is -- it may be sufficient for simple purposes, and if not, there's always `boost::filesystem`. The `<experimental/filesystem>` header is included in the distro so it would be nice to have the matching library too so things don't just fail at link time.

**Comment by tcbrindle** [comment]
Ooops, looking at this more closely, it seems I was mistaken -- the `<experimental/filesystem>` header does not seem to be included in GCC on Windows (I swear this failed at link time when I tried it though!).

If the headers aren't available then I can't complain about missing symbols. Closing this report, apologies for the noise :-)

**Comment by StephanTLavavej** [comment]
Heh, no problem.

**Comment by fcharlie** [comment]
GCC 9.1 maybe support filesystem on Windows 
https://github.com/gcc-mirror/gcc/commit/2fd48392d0a4ac3d1e217367ccb0ec0333d584d8
