### ISSUE TITLE
multilib zlib build broken. wrong path to prev-gcc

### ISSUE THREAD

**Issue by keenloong** [StephanTLavavej/mingw-distro#25]
Hi ,I wanna compile mingw64 with 32bit support ,so I follow your instruction and modified the --disable-multilib with enabled, but when I run your mingw64+gcc.sh one by one in msys2_shell.cmd, I compile gmp,mpfr ,mpc and mingw64 successfully . but when it comes to gcc6.1 compiling,I got error as follow:

``checking for x86_64-w64-mingw32-gcc... /c/temp/gcc/build/32/./prev-gcc/xgcc -B/c/temp/gcc/build/32/./prev-gcc/ -B/c/temp/gcc/dest/x86_64-w64-mingw32/bin/ -L/c/temp/gcc/dest/x86_64-w64-mingw32/lib -L/c/temp/gcc/dest/mingw/lib -isystem /c/temp/gcc/dest/x86_64-w64-mingw32/include -isystem /c/temp/gcc/dest/mingw/include -B/c/temp/gcc/dest/x86_64-w64-mingw32/bin/ -B/c/temp/gcc/dest/x86_64-w64-mingw32/lib/ -isystem /c/temp/gcc/dest/x86_64-w64-mingw32/include -isystem /c/temp/gcc/dest/x86_64-w64-mingw32/sys-include  -m32
checking for suffix of object files... configure: error: in `/c/temp/gcc/build/32/zlib':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
make[2]: *** [Makefile:10811：configure-stage2-zlib] error 1

My prev-gcc directory is under /c/temp/gcc/build not under /c/temp/gcc/build/32  It seems that zlib's configure cannot find xgcc correctly, I google it and only find that's an old bug [bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=29557), I don't know how to fix it ,could you please help me or anyone see this give some advice? I'm not familiar with gnu's autoconf and automake grammar.

Thank you.

**Comment by StephanTLavavej** [comment]
I'm opposed to 32-bit targeting and can't help you, sorry.
