### ISSUE TITLE
GDB 7.11 is not the newest version anymore

### ISSUE THREAD

**Issue by MoreAxes** [StephanTLavavej/mingw-distro#27]
GDB 7.12 was released recently, introducing (among other things) native Rust support. Since yours seems to be the only working binary GDB release for Windows out there, I would urge you to update the distro - myself and likely many Rust developers on Windows would be grateful, as GDB is currently the only mature Rust debugger.

NB, I had a go (several, actually) at building GDB on my own; sadly, all of my attempts failed.

**Comment by StephanTLavavej** [comment]
I'm working on a new distro now.
