### ISSUE TITLE
Boost.Context is hostile to MinGW, also breaking Boost.Coroutine and Boost.Coroutine2

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#3]
Boost.Context's maintainer has refused to support MinGW: https://svn.boost.org/trac/boost/ticket/7262

As a result, Context, Coroutine, and Coroutine2 must all be disabled.

This doesn't actually bother me, except that it makes my build script slightly more complicated. If Context supported MinGW, I would re-enable this stuff.

**Comment by l0calh05t** [comment]
You need MASM on your path to build with MinGW. Seems to work fine, however there are linker warnings.

**Comment by StephanTLavavej** [comment]
I don't have MASM installed. They should use the GNU assembler.
