### ISSUE TITLE
glbinding.patch should be submitted upstream

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#31]
I believe that it's ready to go as-is, I just need to write up the rationale.

**Comment by StephanTLavavej** [comment]
It's not ready to go - std::lock_guard etc. usage has been added in master.

**Comment by scheibel** [comment]
This patch seems interesting, I think we'll integrate this.
See https://github.com/cginternals/glbinding/issues/224.

**Comment by StephanTLavavej** [comment]
Wow, thank you!

**Comment by StephanTLavavej** [comment]
I've updated the patch to apply to 2.1.3 and master, and submitted a pull request. (My first pull request ever!)
