### ISSUE TITLE
Enable OpenMP support

### ISSUE THREAD

**Issue by ismail** [StephanTLavavej/mingw-distro#32]
I know you'll just say use Boost.Thread instead but OpenMP on MinGW is actually stable and quite useful since porting from OpenMP code to Boost.Thread is infeasible for 3rd party code.

**Comment by StephanTLavavej** [comment]
I'm hesitant to do this because not only would I have to figure out how to set it up, I'd have to support it if anything went wrong with it. I made an exception for gdb, but I'm not very eager to continue making such exceptions (admittedly OpenMP is a top request, I just have even less interest in it).

**Comment by ismail** [comment]
Pros: You only need to add a configure option `--enable-libgomp` , nothing else is needed.
Cons: Who is going to support it?

So I suggest enabling it as a "preview" for the next release and say it might go away in a future release and disclaim support. And in the next+1's release you can disable it if it's too much hassle. From the unscientific data I have from openSUSE MinGW project (https://build.opensuse.org/project/show/windows%3Amingw%3Awin64) is that I never see an OpenMP bug report.

**Comment by StephanTLavavej** [comment]
I'll consider this for distro 15.0. Too much was changing in 14.1 for me to be comfortable doing this.

**Comment by StephanTLavavej** [comment]
```
checking for uint64_t... yes
checking what to include in gstdint.h... stdint.h (already complete)
configure: error: Pthreads are required to build libgomp
make[2]: *** [Makefile:22883: configure-stage1-target-libgomp] Error 1
make[2]: Leaving directory '/c/temp/gcc/build'
make[1]: *** [Makefile:24644: stage1-bubble] Error 2
make: *** [Makefile:25045: bootstrap] Error 2
gcc 2 - EPIC FAIL
```

**Comment by RoyiAvital** [comment]
Hi,

Any chance you reconsider this?

Thank You.

**Comment by StephanTLavavej** [comment]
I believe I can enable winpthreads and OpenMP in distro 15.2.

**Comment by RoyiAvital** [comment]
Perfect,

I saw @dokipen3d work.
Really the spirit of Open Source.

Thank You.
