### ISSUE TITLE
Shell?

### ISSUE THREAD

**Issue by JoeArizona** [StephanTLavavej/mingw-distro#36]
Hi Stephan – Maybe a dumb question, but is there a shell included in your distro? I didn't see one.

**Comment by StephanTLavavej** [comment]
My distro intentionally consists of mingw-w64 only, with batch files for use through the Windows Command Prompt. If you want MSYS2's bash shell, you can install that separately. I use MSYS2 to bootstrap the distro (i.e. build GCC with itself), so I provide instructions in my README for getting MSYS2 set up without running an installer. Note that MSYS2 can install a build of mingw-w64; I have never used that.

**Comment by JoeArizona** [comment]
Thanks. By the way, which exception handling system does the distro use? SJLJ or SEH?

**Comment by StephanTLavavej** [comment]
SEH.
