### ISSUE TITLE
Which MinGW?

### ISSUE THREAD

**Issue by JoeArizona** [StephanTLavavej/mingw-distro#37]
Hi Stephan – I just need a little clarification/context on which MinGW this is. The official [MinGW-w64 page](https://sourceforge.net/projects/mingw-w64/files/?source=navbar) on SourceForge offers eight versions as seen in the screenshot below:

![mingw list](https://cloud.githubusercontent.com/assets/8071692/25457675/edbdb6d6-2a8b-11e7-8b09-7a7205e961cf.PNG)

Which of these does your MinGW distro match most closely?

Auxiliary question: What's with the win32 vs POSIX distinction in this context? These are all intended to run and compile stuff on Windows. Do the POSIX versions create some sort of POSIX subsystem similar to cygwin or the Linux subsystem that Microsoft has added to Windows 10?

Thanks for your help.

**Comment by StephanTLavavej** [comment]
My distro is x64-native, so it's x86_64 in their terminology. I use SEH for C++ exception handling (as indicated in the configure scripts by neither enabling nor disabling SJLJ). And I don't attempt to build POSIX wrappers over the Win32 threading API. So I believe x86_64-win32-seh corresponds to my distro.

This sort of confusion is why I maintain my own distro.
