### ISSUE TITLE
Investigate code signing

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#39]
It's unclear to me how much of a problem it is that my self-extracting archives and distro executables are unsigned. It's also unclear how obnoxious it would be to set up code signing.

**Comment by RoyiAvital** [comment]
Any chance you share a ZIP file instead of executable as installer?
This will solve the installer.

About the other executable, it would be great to have them signed.

**Comment by StephanTLavavej** [comment]
If you have 7-Zip installed, it can extract self-extracting archives without running them, so I see minimal value in providing a zip.

**Comment by StephanTLavavej** [comment]
In my Win10 VM, Edge didn't complain about downloading and running my SFX.
