### ISSUE TITLE
coreutils is relentlessly hostile to MinGW

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#4]
`coreutils.sh` is my worst build script, by far. It contains a huge number of terrible hacks, and salvages `sort`, `uniq`, and `wc` from the build's flaming wreckage.

It would be nice if fewer hacks were necessary.

**Comment by StephanTLavavej** [comment]
https://github.com/uutils/coreutils is probably my best bet here, assuming MSYS2 can retrieve a Rust compiler.

**Comment by Et7f3** [comment]
What replace coreutils now ?

**Comment by StephanTLavavej** [comment]
I'm replacing it with https://github.com/uutils/coreutils which I was able to successfully build.
