### ISSUE TITLE
Feature request: develop branch with gcc SVN tip-of-trunk support

### ISSUE THREAD

**Issue by rhalbersma** [StephanTLavavej/mingw-distro#44]
Given that gcc is on a yearly release cycle and your distro more or less folllows Boost's 4 month cycle, would it be an idea to also track the latest gcc SVN tip-of-trunk? This would get the newest C++ features to your users earlier. Perhaps in a git develop branch, so that upon the official release, you can merge it into master?

**Comment by StephanTLavavej** [comment]
It's a nice idea, but distro maintenance is already time-consuming and I just don't have any more free time. I encourage you to maintain a fork of my build scripts and try this out.
