### ISSUE TITLE
-m32 parameter invalid

### ISSUE THREAD

**Issue by ashi876** [StephanTLavavej/mingw-distro#47]
-m32 command invalid。
The official version is OK

**Comment by StephanTLavavej** [comment]
My distro is intentionally 64-bit only. I am opposed to 32-bit's existence.

**Comment by PiotrGrochowski** [comment]
I am uninstalling your MinGW because of this

**Comment by PiotrGrochowski** [comment]
I uninstalled your MinGW already. It is absolutely useless.

**Comment by badrelmers** [comment]
>  I am opposed to 32-bit's existence

Why marginalize something alive and existing :(
you are a dictator :)
please add 32 support not everybody have a 64 system

**Comment by Et7f3** [comment]
32 bits tends to disappears. Some linux distro dropped support like Arch. Some compiler drop support. Visual studio 2022 is x64 only...

Maybe I am too young but I never touched a 32bits system.

**Comment by viccpp** [comment]
> please add 32 support not everybody have a 64 system

https://github.com/niXman/mingw-builds-binaries/releases

**Comment by StephanTLavavej** [comment]
I have spoken.
