### ISSUE TITLE
binutils 2.30 triggers an ICE in gcc bootstrap

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#51]
binutils 2.29.1 works, but binutils 2.30 consistently triggers:

```
make[3]: Entering directory '/c/temp/gcc/build/gcc'
/c/temp/gcc/build/./gcc/xgcc -B/c/temp/gcc/build/./gcc/ -nostdinc -x c /dev/null -S -o /dev/null -fself-test=../../src/gcc/testsuite/selftests
cc1.exe: internal compiler error: in initialize, at alloc-pool.h:257
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[3]: *** [Makefile:1933: s-selftest] Error 1
```

**Comment by ssbssa** [comment]
binutils 2.30 is broken for mingw, see [binutils bug #22762](https://sourceware.org/bugzilla/show_bug.cgi?id=22762).
It's fixed in git already.

**Comment by StephanTLavavej** [comment]
Thanks! That's exactly the information I was looking for. It appears that 2.30.1 (if it is released) will contain the fix too.

**Comment by ssbssa** [comment]
On that note, gdb 8.1 for win64 has a relatively bad bug as well: [gdb bug #22854](https://sourceware.org/bugzilla/show_bug.cgi?id=22854)
