### ISSUE TITLE
considering to add openssl?

### ISSUE THREAD

**Issue by PhDunski** [StephanTLavavej/mingw-distro#52]
First, I would like to thak you for your great job; your distro is definitively one of my prefered, since it holds many prebuild external libraries and provide a very up-to-date Gcc version.

But it is on which could be interresting to add to your distro as openssl.

It is a very interesting cryptographic C library, often used by developpers (sometimes even very juniors), but compiling it should require Msys2 and some knowledge that some people don't have (yet).

What do you think about this idea?

**Comment by StephanTLavavej** [comment]
I'm glad you like my distro. Unfortunately, I don't have enough free time to add and maintain libraries I don't use. (I've already made a small number of exceptions for gdb and winpthreads; I can't keep making more.) You're welcome to develop your own build script for openssl, using my build environment and existing scripts as a base - that way you can still use my distro for the bulk of the work, and add any other components you want.
