### ISSUE TITLE
libdl.a not exist

### ISSUE THREAD

**Issue by wjx0912** [StephanTLavavej/mingw-distro#54]
hi, 
i just switch from msys2 to  nuwen-mingw,   in msys2, the libdl.a and dlfcn.h exist, but not in nuwen-mingw.
why delete this file?  it's useful for some project.

here is my error when build etcd on golang(windows use nuwen-mingw):
`c:/mingw-nuwen/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
collect2.exe: error: ld returned 1 exit status`

wish your reply, thanks.

**Comment by StephanTLavavej** [comment]
Apparently this is https://github.com/dlfcn-win32/dlfcn-win32 , which I have no interest in building, but you can build it yourself if you like.
