### ISSUE TITLE
GDB and expat

### ISSUE THREAD

**Issue by MarcelHB** [StephanTLavavej/mingw-distro#55]
Hello,

I noticed that `gdb` is not compiled with libexpat. It looks as if this is the reason you cannot really use `gdb` on Windows programs using shared libraries, `info sharedlibrary` never lists anything and stacktraces remain useless for such purposes.

Unfortunately, just adding `--with-expat` to the build script did not work for me locally, making `./configure` fail for lots of other reasons, using 15.4 and MSYS2, otherwise I'd come up with a patch.

Is there a feasible solution? Cause aside from that, you provide the most sane and up-to-date GCC distribution for Win64 out there. :slightly_smiling_face: 

Regards

**Comment by StephanTLavavej** [comment]
I don't use gdb myself - I just build it in the hopes that people will stop complaining about its absence. I welcome patches to improve it, but I don't have enough free time to investigate this myself.

**Comment by MarcelHB** [comment]
Ok, thanks.
