### ISSUE TITLE
Issue Compiling libpng With GCC 8.1.0

### ISSUE THREAD

**Issue by MrM21632** [StephanTLavavej/mingw-distro#60]
Another issue that's arisen recently: libpng throws an error similar to this when compiling with GCC 8.1.0:

```
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../src     -O3 -s -MT contrib/libtests/pngvalid.o -MD -MP -MF $depbase.Tpo -c -o contrib/libtests/pngvalid.o ../src/contrib/libtests/pngvalid.c &&\
mv -f $depbase.Tpo $depbase.Po
C:\mingw_distro_setup\msys64\tmp\ccAnQqvS.s: Assembler messages:
C:\mingw_distro_setup\msys64\tmp\ccAnQqvS.s:33889: Error: .seh_savexmm offset is negative
C:\mingw_distro_setup\msys64\tmp\ccAnQqvS.s:33890: Error: .seh_savexmm offset is negative
C:\mingw_distro_setup\msys64\tmp\ccAnQqvS.s:33895: Error: .seh_savexmm offset is negative
C:\mingw_distro_setup\msys64\tmp\ccAnQqvS.s:33896: Error: .seh_savexmm offset is negative
make[1]: *** [Makefile:1159: contrib/libtests/pngvalid.o] Error 1
make[1]: Leaving directory '/c/mingw_distro_setup/build'
```

The current workaround is to pass `-fno-asynchronous-unwind-tables` to GCC when compiling, as per [this bug report](https://sourceforge.net/p/libpng/bugs/280/).

**Comment by StephanTLavavej** [comment]
Ugh, thanks for letting me know. This is also [GCC Bug 86048](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86048).

**Comment by richardebel** [comment]
Thanks.  Simple C++ programs will compile successfully, but wont run(segment fault) without the GCC patch:

#include <iostream>

int main(){
	std::cout << "Hello World\n";
	std::cin.get();
	return 0;
}
