### ISSUE TITLE
Can you use authenticode or similar to make it less hassle to install on Win10?

### ISSUE THREAD

**Issue by JoeUX** [StephanTLavavej/mingw-distro#61]
Hi Stephan – Windows 10 valiantly resists installing your distro, and I'm just wondering if you could make it easier by using Authenticode or similar signing.

**Comment by StephanTLavavej** [comment]
I've looked into this briefly, and the process appears to be relatively onerous (not just obtaining the certificate, but also just invoking the tools), so I have no current plans to do so. If the tool situation has improved, I'd reconsider.

As of a few months ago, I was able to install my distro in a Win10 VM relatively painlessly, via Edge. If you get warnings about unsigned executables, there is an escape hatch, although you have to click on the prompts to reveal the option (they want to make it difficult for non-technical users to get into trouble).

Note that 7-Zip's self-extracting archives can simply be extracted via 7-Zip without running them.
