### ISSUE TITLE
GCC 9.1 support soon?

### ISSUE THREAD

**Issue by oscarbg** [StephanTLavavej/mingw-distro#67]
asking similar to one year ago :-)
https://github.com/StephanTLavavej/mingw-distro/issues/59

**Comment by frnidito** [comment]
+1

**Comment by ashi876** [comment]
+1

**Comment by StephanTLavavej** [comment]
I've been busy with personal life lately, but I haven't forgotten about this. Hang in there! :cat:

**Comment by StephanTLavavej** [comment]
I'm aware that GCC 9.2 has been released, and I'm working on this (slowly).

**Comment by bleuge** [comment]
Come here looking for this!, many thanks!

**Comment by HuangShumin** [comment]
can GCC 9.2 be available this year? thanks

**Comment by StephanTLavavej** [comment]
I have been extremely busy with work and personal matters, but yes, I will try to release a new distro this year.

**Comment by HuangShumin** [comment]
Sincerely thanks for your devotion!

**Comment by StephanTLavavej** [comment]
Progress:

- [x] binutils 2.33.1
- [x] Boost 1.71.0
- [x] FreeType 2.10.1
- [x] GCC 9.2.0
- [x] gdb 8.3.1
- [x] mingw-w64 7.0.0
- [x] zstd 1.4.4
- [ ] 7-Zip
- [ ] coreutils
- [ ] git
- [ ] glbinding
- [ ] GLM
- [ ] libjpeg-turbo
- [ ] libogg
- [ ] libpng
- [ ] PCRE
- [ ] PCRE2
- [ ] SDL
- [ ] Consider adding GLFW

**Comment by StephanTLavavej** [comment]
Distro 17.0 is now available, containing GCC 9.2, the latest released version. Thanks for using my distro, and apologies for taking so long.

(You may need to force-refresh the download page; I haven't figured out how to make Apache invalidate caches when I upload new pages.)

**Comment by frnidito** [comment]
This is brilliant, thanks!
