### ISSUE TITLE
Consider adding vcpkg

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#74]
Adding [vcpkg](https://github.com/microsoft/vcpkg) would allow users to easily add additional libraries, instead of requesting them as part of the core distro.

**Comment by cristianadam** [comment]
https://github.com/microsoft/vcpkg/pull/9137 has the necessary changes to vcpkg, and it adds the tripplets, which would allow something like this to work:

```
set VCPKG_TARGET_TRIPLET=x64-mingw
vcpkg install zlib libpng double-conversion pcre2 freetype
```
and then you build your CMake project like:
```
cmake -GNinja ^
  -DVCPKG_TARGET_TRIPLET=x64-mingw ^
  -DCMAKE_TOOLCHAIN_FILE=c:/Projects/github/vcpkg/scripts/buildsystems/vcpkg.cmake
```

**Comment by cristianadam** [comment]
I tested the above with the standalone toolchain from https://gcc-mcf.lhmouse.com/.

**Comment by cristianadam** [comment]
I've updated my https://github.com/microsoft/vcpkg/pull/9137 and #72 is no longer blocking. Two tests are failing, but I was able to do a:
```
vcpkg install zlib:x64-mingw
```

**Comment by StephanTLavavej** [comment]
This has been merged upstream, so I should be able to add vcpkg to the distro now.

**Comment by StephanTLavavej** [comment]
Now that I have slightly more experience with vcpkg, I don't believe that adding `vcpkg.exe` to the distro would be useful.

What users need to do is use vcpkg as a submodule, bootstrap it, and then they can build current versions of their desired libraries ("ports") corresponding to their submodule commit.
