### ISSUE TITLE
integration with windows terminal

### ISSUE THREAD

**Issue by GautamDMan** [StephanTLavavej/mingw-distro#75]
Hi.

I am trying to get a new tab settings to work for your Mingw distro using the "set_distro_paths.bat" in the cmd to set the env vars. Is there any setting I can use to set this distro paths when a new cmd instance is spawned in the terminal. 

I have tried below setting, but with no success::

{
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6111}",
            "name": "cmd",
            "commandline": "cmd.exe /k 'C:\MinGW\set_distro_paths.bat'",
			"colorScheme": "One Half Dark",
			"startingDirectory": "%USERPROFILE%\\Desktop",
            "hidden": false
        },

the error i keep getting is :
![err](https://user-images.githubusercontent.com/2228569/71553729-4dcd6e80-2a3a-11ea-97c6-01acf5fc563b.jpg)

Any suggestions to set these paths alternatively ?

**Comment by StephanTLavavej** [comment]
I don't know what line 26, column 28 of your file is. It might be the single-quoted `'C:\MinGW\set_distro_paths.bat'`. I haven't used the Windows Terminal, but reading https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md leads me to believe that you shouldn't be using single quotes here, and should instead be using double backslashes: `C:\\MinGW\\set_distro_paths.bat`. The same may apply to the `startingDirectory`.

**Comment by GautamDMan** [comment]
oh yeah yeah !! that worked perfectly. 

my setting now::

{
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6123}",
            "name": "NUWEN-GCC",
            "commandline": "cmd.exe /k C:\\MinGW\\set_distro_paths.bat",
	    "icon" : "C:/MinGW/gcc-icon.png",
	    "colorScheme": "One Half Dark",
	    "startingDirectory": "%USERPROFILE%\\Desktop",
            "hidden": false
        },

UI::
![it-works](https://user-images.githubusercontent.com/2228569/71556541-f7732680-2a5f-11ea-9337-cd75169a83fc.jpg)

Thanks a lot !!
