### ISSUE TITLE
Trademark Infringement

### ISSUE THREAD

**Issue by 289aincwaeubr** [StephanTLavavej/mingw-distro#76]
Hi there, my name is 289aincwaeubr. Your compiler infringes the trademark of an existing compiler named MinGW. As such, you can't name your compiler MinGW. Try generating a random name and ensuring it's not an existing trademark.

**Comment by StephanTLavavej** [comment]
This is a set of build scripts to build a distribution of [mingw-w64](http://mingw-w64.org/doku.php). It does not claim to be mingw-w64, and the build scripts are useless without mingw-w64’s source code, obtained from their website.
