### ISSUE TITLE
GCC 9.3 support

### ISSUE THREAD

**Issue by anb0s** [StephanTLavavej/mingw-distro#79]
As GCC 9.3 was released, it would be good to have the distro updated.

Thanks for the great distro 👍

**Comment by StephanTLavavej** [comment]
I may have time for this later this month, although it’s more likely I’ll wait for GCC 10.

**Comment by anb0s** [comment]
Thank You! 9.x has some regressions i've faced for C++ code and they are fixed in 9.3 and 8.4.  
The major 10 release will bring some more new ;)

**Comment by StephanTLavavej** [comment]
Ah, I’ll see what I can do then.

**Comment by StephanTLavavej** [comment]
Superseded by #83.
