### ISSUE TITLE
uilding GCC 9.3 meet some error

### ISSUE THREAD

**Issue by Efreets** [StephanTLavavej/mingw-distro#81]
Hi,
Do you have some time to help me to solve the problem with building gcc 9.3 on windows?
Thanks.

Here was my information during Build gcc, how it makes, I'm my best to solve the error, but it's no work

My configure is

../gcc-9.3.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/P/Efreets/gcc930/ --with-sysroot=/P/Efreets/gcc930/ --enable-languages=c,lto,c++,fortran --enable-lto --enable-static --disable-symvers --disable-shared --enable-threads=posix --enable-sjlj-exceptions --with-system-zlib --with-gmp=/P/Efreets/gmp620 --with-mpfr=/P/Efreets/mpfr402 --with-mpc=/P/Efreets/mpc110 --with-isl=/P/Efreets/isl221 --with-zstd=/P/Efreets/zstd144

It's meet this error

[ -f stage_final ] || echo stage3 > stage_final
make[1]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
make[3]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
rm -f stage_current
make[3]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
/usr/bin/sh: -c:行6: unexpected EOF while looking for matching `''
/usr/bin/sh: -c:行7: syntax error: unexpected end of file
make[2]: *** [Makefile:11206: all-stage1-libiberty] Error 1
make[2]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[1]: *** [Makefile:21113: stage1-bubble] Error 2
make[1]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make: *** [Makefile:1003: all] Error 2

And this is the error line in MakeFile
![eff889e3d134e9e2d88fbbae7fb15c79](https://user-images.githubusercontent.com/11472828/78437880-9e8fdb80-76a9-11ea-9ead-26c9b72677ae.png)

![76f4fa84a85768a6c2482d160c8b1d07](https://user-images.githubusercontent.com/11472828/78437978-a64f8000-76a9-11ea-8891-95076e298ee4.png)

I think error line in right, but I can't solve the problem, could you help me ?

I can't thank you so much, I need you help, Waiting message.

yours sincerely

**Comment by Efreets** [comment]
I'm new to building the gcc9.3, and didn't have the experience for the gnu soft building, didn't know why this happend, if you know how to solve, help me, please.
Thanks.

**Comment by Efreets** [comment]
Makefile is the error file by make said, I also think may be the PWD_COMMAND = $${PWDCMD-pwd} was not work correct, because is't not send the pwd path value to the r, it does relay the source path to the system environment, but I don't know why, I'm Building under msys2, I distrust my msys2, because I built another gnu soft, like binutils, also meet the unexpected EOF while looking for matching `'' error, I didn't solve this problem, I need why that happend, I need your help, if you know how to solve.

the Makefile I changed, and this was the happend
![捕2获](https://user-images.githubusercontent.com/11472828/78440329-51603980-76aa-11ea-9394-dd633f93684a.PNG)
![捕获](https://user-images.githubusercontent.com/11472828/78440422-57eeb100-76aa-11ea-956d-cf64a2ead532.PNG)

**Comment by StephanTLavavej** [comment]
I'm unable to help with MSYS2 environment problems, sorry.
