### ISSUE TITLE
GCC 11.2 support

### ISSUE THREAD

**Issue by oscarbg** [StephanTLavavej/mingw-distro#83]
just asking to keep notified when it's supported :-)

**Comment by oscarbg** [comment]
just renamed to GCC 10.2.. hope it's coming somewhat soon.. :-)

**Comment by StephanTLavavej** [comment]
I'm currently dealing with PC hardware issues, but hopefully I'll be able to fix them and update the distro by the end of this accursed year.

**Comment by oscarbg** [comment]
any update?

**Comment by StephanTLavavej** [comment]
My PC works now, I just need to find a free weekend. Life has been busy.

**Comment by RoyiAvital** [comment]
@StephanTLavavej , It will be great to see your distribution updated.
Just know there are many waiters :-).

**Comment by StephanTLavavej** [comment]
I worked on the distro this weekend and got a bunch of components updated (binutils 2.37, Boost 1.77.0, FreeType 2.11.0, GCC 11.2.0, gdb 10.2, GLFW 3.3.4, grep 3.7, libjpeg-turbo 2.1.1, libogg 1.3.5, libvorbis 1.3.7, mingw-w64 9.0.0, PCRE 8.45, PCRE2 10.37, SDL 2.0.16, sed 4.8, vorbis-tools 1.4.2, zstd 1.5.0). I have about a dozen more tasks to finish (other components to update/add/etc.). No promises, but it might be one or two weekends away. (Building GCC is the hardest part and that's done.)

**Comment by wehostadm** [comment]
Hi Stephan,

Does the new version of Nuwen ready ? I currently use the last version on your website : 
https://nuwen.net/mingw.html

Thanks for your hard work,

**Comment by wehostadm** [comment]
@StephanTLavavej Looking forward the result of the new distro. Thanks for your work !

**Comment by wehostadm** [comment]
Hi Stephan,
I just want to know if you will have time to finsh the final packaging this week-end ?
Thanks a lot

**Comment by StephanTLavavej** [comment]
Distro 18.0 containing GCC 11.2 is now available. (You may need to refresh my webpage.)
