### ISSUE TITLE
How to use mingw-distro with fsanitize=address and -fsanitize=undefined?

### ISSUE THREAD

**Issue by CaptainDredge** [StephanTLavavej/mingw-distro#84]
I got following error while using above mentioned flags 
`c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lasan
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lubsan
collect2.exe: error: ld returned 1 exit status`

**Comment by StephanTLavavej** [comment]
The sanitizers aren't supported by MinGW-w64 yet, see https://www.mingw-w64.org/contribute/#sanitizers-asan-tsan-usan .

If they add support, and I can enable it in the distro without too much effort, I'll do so.
