### ISSUE TITLE
GCC 11 support

### ISSUE THREAD

**Issue by wjx0912** [StephanTLavavej/mingw-distro#85]
https://linuxreviews.org/GCC_11_Will_Be_Set_In_Stone_On_November_15th

the gcc11 will release immediately, wish your great job, thanks

**Comment by wjx0912** [comment]
https://gcc.gnu.org/

gcc 11.1 release

**Comment by StephanTLavavej** [comment]
Duplicate of #83, see my update there: https://github.com/StephanTLavavej/mingw-distro/issues/83#issuecomment-917921046 .
