### ISSUE TITLE
Please add libtiff to the distro

### ISSUE THREAD

**Issue by jointri** [StephanTLavavej/mingw-distro#87]
One thing that seems to be missing to me is libtiff and it be really convenient if libtiff was included with this distro. Could you please add libtiff?

**Comment by StephanTLavavej** [comment]
No, sorry. Every component takes time to maintain, and I barely have enough free time to maintain the current distro. I recommend either building libtiff yourself - you can use my build scripts as an example of how to get started - or use [vcpkg](https://github.com/microsoft/vcpkg) with mingw-w64 as the "target triple".
