### ISSUE TITLE
grep 3.7 crashes without `-P`

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#89]
In distro 18.0, grep 3.7 crashes without `-P`. I'm not sure when this started happening (it took me a while to notice because I usually use `-P`).

**Comment by ChristopherHeng** [comment]
Hi Stephan, just to let you know that I have been using grep 3.7 from your nuwen distro without issue, and without -P. I say this so that you don't waste time trying to debug the wrong thing. (Maybe your installed binary was corrupted or something?)

**Comment by StephanTLavavej** [comment]
I'm still not sure what happened here - I still repro it with grep 3.7 - but it appears to be fixed in grep 3.11.
