### ISSUE TITLE
glew-core.patch is still needed to support OpenGL core profiles in GLEW

### ISSUE THREAD

**Issue by StephanTLavavej** [StephanTLavavej/mingw-distro#9]
It's 2015 and GLEW still doesn't support OpenGL core profiles. `glew-core.patch` is my robust fix, but I shouldn't have to maintain this.

I would be open to switching libraries (as I previously switched from GLee to GLEW), but I'm not currently familiar with what's available.

**Comment by sol-prog** [comment]
GLAD is a cleaner option than GLEW, here are the most used loader libraries for OpenGL https://www.opengl.org/wiki/OpenGL_Loading_Library

**Comment by LB--** [comment]
It looks like GLEW has a separate branch for this that is in the works:
https://github.com/nigels-com/glew/pull/30
Maybe you can build from that branch instead of using the patch?

**Comment by StephanTLavavej** [comment]
@sol-prog , GLAD looks interesting, although I'm wary of anything that doesn't call itself 1.0. Previously the Python prerequisite would have been a deal-breaker, although I think MSYS2 might have an installer-free package (need to investigate).

@LB-- , my usual policy is to stick to official releases only, not pre-release or development branch versions. I have more confidence in my patch than in pre-release code.

**Comment by StephanTLavavej** [comment]
http://sourceforge.net/p/glew/bugs/174/ has been fixed for GLEW 2.0.0, *finally*.
