### ISSUE TITLE
Upgradation

### ISSUE THREAD

**Issue by Spidy104** [StephanTLavavej/mingw-distro#90]
When will the whole distro set be upgraded or has it been deprecated??

**Comment by StephanTLavavej** [comment]
I'll try to find some free time this summer.

**Comment by fdiedler** [comment]
Hi @StephanTLavavej 

Will the distro be updated with the last gersion of GCC ? 
I use it for many years in my IA project and you have done a good job, many thanks ;)

Hope this distro will not be deprecated...

**Comment by StephanTLavavej** [comment]
I'm still planning to update it, I just need to find a free weekend.

**Comment by fdiedler** [comment]
@StephanTLavavej Did you have time to upgrade your distro ? Thanks

**Comment by oscarbg** [comment]
+1

**Comment by fdiedler** [comment]
@StephanTLavavej Hi, will you upgrade or not your distro ? I use it in my IA project and your distro is really good :)
Thanks

**Comment by StephanTLavavej** [comment]
I do intend to upgrade it, hopefully this year, but I have been *extremely* busy and the distro is near the bottom of my priority list. Sorry.

**Comment by wehostadm** [comment]
@StephanTLavavej 
I am also looking for an upgradation for this wonderful package :)
Hope you will have time to upgrade it with the last stable versions of GCC/G++ and libraries 
Thanks

**Comment by AndrewSav** [comment]
It would be nice if this could be kept up to date, gcc 12 is what we need ;)

**Comment by StephanTLavavej** [comment]
I might try to build an updated distro soon (no promises).

**Comment by AndrewSav** [comment]
@StephanTLavavej I had a look at helping, but this repo has patches with no explanation why they are needed, so it's hard to judge if they should be carried over (and why).

**Comment by StephanTLavavej** [comment]
@AndrewSav Thank you!! I started working on the distro build and encountered that exact issue with Boost.URL. This will really help!

Some of the patches in the repo (glbinding, binutils) are from PRs that were merged and are no longer necessary after upgrading. Other patches are hacks I've developed over time to just get the stuff building (most notably coreutils, which I will be attempting to completely replace this cycle). My elusive goal is to get the distro to build patch-free. I could indeed have done a better job adding comments. In general, "see what happens without the patch" will give some idea of what it's doing.

**Comment by AndrewSav** [comment]
> In general, "see what happens without the patch" will give some idea of what it's doing.

I was not so sure about that when looked at the big `mpfr` patch. I thought it might be not because it would not compile, just because you were hitting an issue with some software you built using that library, so you patched it.

**Comment by StephanTLavavej** [comment]
Oh, that was an "official" patch from the website - they sometimes include it on their webpage instead of making proper point releases. The current version doesn't appear to have such a patch, so I'm dropping it.

**Comment by StephanTLavavej** [comment]
Status update: I spent the last part of my winter vacation working on this, and I've updated all components with only 7-Zip (easy) and coreutils remaining. For coreutils I want to try a complete replacement. No ETA yet but I'll try to return to this next weekend as I'm close.

**Comment by AndrewSav** [comment]
I would be interested in submitting a PR to make this run on GitHub actions when you are done, to make the next upgrade somewhat easier. Same as you - no commitments, though. Would you be interested?

**Comment by StephanTLavavej** [comment]
I'm not sure how that could save time, and it sounds like it would take work to maintain. I'd say I'm not very interested although I wouldn't reject the idea immediately.

The primary time sink is having to figure out what breaks whenever a new version of a component is released. Sometimes it's trivial, sometimes it takes a while to investigate.

What would help me is getting issues fixed upstream; I've been trying to get better at filing tracking issues in this repo, I just don't have the time to go deal with upstream repos.

**Comment by AndrewSav** [comment]
Fair enough. I agree that 'the primary time sink is having to figure out what breaks whenever a new version of a component is released', for you, but if another person (like me) wants to contribute, they will spend time on scouting where each tar comes from downloading them and and putting them into the right place for the script to pick up. It does not make it easy to help. With the action, you could just update the versions and run the build see where it fails and go from there (what you mentioned). You could run the script locally as well.

But if you do not see value in this, fine by me.

> What would help me is getting issues fixed upstream

Yeah, I personally have quite a dim view on the success chance here, and is not ready to take on what I view as almost hopeless enterprise.

**Comment by StephanTLavavej** [comment]
Distro 19.0 is now available - enjoy!
